version: "3.9"
services:
  forcast:
    image: ghcr.io/ccmbioinfo/forcast:stable
    ports:
      - 80:80
      - 443:443
    tmpfs:
      - /run/apache2
      - /run/mongodb
      - /run/lock
      - /tmp
    volumes:
      - ./logs:/var/log/FORCAST
      - ./config:/var/www/html/config
      - ./docs:/var/www/html/docs
      - ./jbrowse/data:/var/www/html/jbrowse/data
      - ./jbrowse/plugins/ColorByCDS:/var/www/html/jbrowse/plugins/ColorByCDS
      - ./jbrowse/plugins/ExportSequence:/var/www/html/jbrowse/plugins/ExportSequence
      - ./apache2/certs:/etc/apache2/certs
      - ./apache2/sites-enabled/forcast-ssl.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./src:/var/www/html/src
      - mongodb:/var/lib/mongodb
volumes:
  mongodb:
# docker-compose exec forcast ./src/setup/setup.sh 106 Saccharomyces_cerevisiae R64-1-1
