version: "3.9"
services:
  forcast:
    build: .
    image: ghcr.io/ccmbioinfo/forcast
    ports:
      - 80:80
    tmpfs:
      - /run/apache2
      - /run/mongodb
      - /run/lock
      - /tmp
    volumes:
      - ./sites-enabled:/etc/apache2/sites-enabled
      - ./docs:/var/www/html/docs
      - ./src:/var/www/html/src
      - ./jbrowse/data:/var/www/html/jbrowse/data
      - ./jbrowse/plugins/ColorByCDS:/var/www/html/jbrowse/plugins/ColorByCDS
      - ./jbrowse/plugins/ExportSequence:/var/www/html/jbrowse/plugins/ExportSequence
      - ./crispr-icon.png:/var/www/html/crispr-icon.png
      - ./index.html:/var/www/html/index.html
      - mongodb:/var/lib/mongodb
volumes:
  mongodb:

# After startup, exec into the container and run
# cd /var/www/html/src/setup
# python3 setup.py -r /var/www/html -g Saccharomyces_cerevisiae -v R64-1-1 -fa2bit /var/www/html/bin/faToTwoBit -b /usr/bin
