ATTEMPT_0_FILE=primer3settings/standard_settings.txt
ATTEMPT_1_FILE=primer3settings/Retry1.txt
ATTEMPT_1_DESC="Attempt to design primers failed with default settings from Primer3. Refer to the documentation on how to set custom Primer3 settings for the initial primer design and subsequent attempts after a failure."
